import { Achievement } from "./types";

export const achievementsData: Achievement[] = [
  // Achievements
  {
    id: "ach-1",
    title: "Solveathon 5.0 Hackathon",
    badge: "Winner",
    category: "Achievements",
    event: "Solveathon 5.0 Grand Finale | Pitch Fest Award Ceremony",
    date: "2026",
    description: "Secured First Place / Winner in Solveathon 5.0 Hackathon for innovative security and software solution implementation.",
    recognition: "First Place / Winner",
    photo: {
      src: "/images/achievements/solveathon-5.0.jpg",
      alt: "Solveathon 5.0 Grand Finale Pitch Fest Award Ceremony Winner Photo",
      isPlaceholder: false,
    },
  },
  {
    id: "ach-2",
    title: "Build2Gather Mini AI Hackathon",
    badge: "Winner",
    category: "Achievements",
    event: "Build2Gather AI & Startup Evaluathon",
    date: "2026",
    description: "Awarded Certificate of Achievement at the Mini Build2Gather AI & Startup Evaluathon for technical excellence and innovative project execution.",
    recognition: "Award Winner",
    photo: {
      src: "/images/achievements/build2gather.jpg",
      alt: "Build2Gather AI & Startup Evaluathon Certificate Photo",
      isPlaceholder: false,
    },
  },
  {
    id: "ach-3",
    title: "Smart India Hackathon (SIH)",
    badge: "Finalist",
    category: "Achievements",
    event: "Smart India Hackathon (SIH)",
    date: "2024",
    description: "Selected as National Finalist in Smart India Hackathon (SIH) addressing complex real-world software and security challenges.",
    recognition: "National Finalist",
    photo: {
      src: "/images/achievements/sih-finalist.jpg",
      alt: "Smart India Hackathon Finalist Team Photo",
      isPlaceholder: false,
    },
  },
  {
    id: "ach-4",
    title: "Public Speaking & Debate Competitions",
    badge: "Multiple Time Winner",
    category: "Achievements",
    event: "Inter-College Debate & Public Speaking Competitions",
    date: "2023 - 2024",
    description: "Consistently won top honors across multiple public speaking and debate tournaments.",
    recognition: "Multiple Winner",
    photo: {
      src: "/images/achievements/public-speaking.jpg",
      alt: "Public Speaking & Debate Competition Photo",
      isPlaceholder: false,
    },
  },
  {
    id: "ach-5",
    title: "Sairam Sparkle Culturals Winner",
    badge: "Overall Trophy Winner",
    category: "Achievements",
    event: "Sairam Sparkle 2026 Culturals",
    date: "2026",
    description: "Awarded the Sairam Sparkle 2026 Overall Trophy Winner for outstanding performance across inter-college cultural competitions.",
    recognition: "Overall Winner",
    photo: {
      src: "/images/achievements/sparkle-culturals.jpg",
      alt: "Sairam Sparkle 2026 Overall Trophy Winner Photo",
      isPlaceholder: false,
    },
  },

  // Recognition
  {
    id: "rec-1",
    title: "Women in CyberSecurity College Chapter Vice Chair",
    badge: "Vice Chair & Student Chapter Leader",
    category: "Recognition",
    event: "WiCyS Student Chapter Leadership",
    date: "2024",
    description: "Served as Vice Chair for the Women in CyberSecurity (WiCyS) Student Chapter, driving chapter growth, organizing technical events, and empowering women in cybersecurity.",
    recognition: "Chapter Vice Chair",
    photo: {
      src: "/images/achievements/wicys-vice-chair.jpg",
      alt: "Women in CyberSecurity College Chapter Vice Chair & Executive Team Photo",
      isPlaceholder: false,
    },
  },
  {
    id: "rec-2",
    title: "Women in CyberSecurity Chapter Mini Hackathon",
    badge: "Hackathon Organizer & Lead",
    category: "Recognition",
    event: "WiCyS Student Chapter Mini Hackathon",
    date: "2024",
    description: "Served as Primary Organizer for the WiCyS Chapter Mini Hackathon, facilitating judging, event execution, and participant mentoring.",
    recognition: "Hackathon Lead",
    photo: {
      src: "/images/achievements/wicys-hackathon.jpg",
      alt: "WiCyS Mini Hackathon Organizer Photo",
      isPlaceholder: false,
    },
  },
  {
    id: "rec-3",
    title: "Sairam Model United Nations",
    badge: "Model United Nations Organizer",
    category: "Recognition",
    event: "Sairam Model United Nations (Sairam MUN)",
    date: "2023",
    description: "Organized and facilitated operations for Sairam Model United Nations conference, receiving recognition for outstanding organizational leadership.",
    recognition: "MUN Organizer & Leadership",
    photo: {
      src: "/images/achievements/sairam-mun.jpg",
      alt: "Sairam Model United Nations Organizer Recognition Photo",
      isPlaceholder: false,
    },
  },
];
